local Errors = {
  TypeIsNotSupported = function(t) return { 'fcpu-errors.type-is-not-supported', t } end,
  UnknownRegister = function(name) return { 'fcpu-errors.unknown-register', name } end,
  CantParseNumber = function(numstr) return { 'fcpu-errors.cant-parse-number', numstr } end,
  UnknownOpcode = function(name) return { 'fcpu-errors.unknown-opcode', name } end,
  UnableToParse = function(str) return { 'fcpu-errors.unable-to-parse', str } end,
  ExpectedOpcodeButRead = function(t) return { 'fcpu-errors.expected-opcode-but-read', t } end,
  WritingUnsupported = function() return { 'fcpu-errors.writing-unsupported' } end,
  UnexpectedType = function(name) return { 'fcpu-errors.unexpected-type', name } end,
  ReadingNil = function(name) return { 'fcpu-errors.reading-nil', name } end,
  UnknownLabel = function(label) return { 'fcpu-errors.unknown-label', label } end,
  WritingToUnknownWire = function(wire) return { 'fcpu-errors.writing-to-unknown-wire', wire } end,
  UnknownMemoryBank = function(bank) return { 'fcpu-errors.unknown-memory-bank', bank } end,
  UnknownChannel = function(channel) return { 'fcpu-errors.unknown-channel', channel } end,
  NotConnectedWire = function(wire) return { 'fcpu-errors.not-connected-wire', wire } end,
  NotConnectedLognet = function() return { 'fcpu-errors.not-connected-lognet', } end,
  ScalarMemoryFull = function(n) return { 'fcpu-errors.scalar-memory-full', n } end,
  UnknownRegisterWithIndex = function(index) return { 'fcpu-errors.unknown-register-with-index', index } end,
  UnknownPrototypeGroup = function(type_name) return { 'fcpu-errors.unknown-prototype-group', type_name } end,
  UnknownPrototype = function(name) return { 'fcpu-errors.unknown-prototype', name } end,

  ExpectingGot = function(msg, type) return { 'fcpu-errors.expecting-got', msg, type } end,
  NotImplemented = function(msg) return { 'fcpu-errors.not-implemented', msg } end,
  ConditionNotMet = function() return { 'fcpu-errors.condition-not-met' } end,
  OpcodeUnavailable = function(modname) return { 'fcpu-errors.opcode-unavailable', modname } end,
  Expecting_1 = function() return { 'fcpu-errors.expecting-1' } end,
  Expecting_2 = function() return { 'fcpu-errors.expecting-2' } end,
  Expecting_ge1 = function() return { 'fcpu-errors.expecting-ge1' } end,
  Expecting_le2 = function() return { 'fcpu-errors.expecting-le2' } end,
  Expecting_2or3 = function() return { 'fcpu-errors.expecting-2or3' } end,
  Expecting_ge2 = function() return { 'fcpu-errors.expecting-ge2' } end,
  Expecting_3 = function() return { 'fcpu-errors.expecting-3' } end,
  Expecting_3or4 = function() return { 'fcpu-errors.expecting-3or4' } end,
  NoAddress =    function(name) return { 'fcpu-errors.no-address', name } end,
  InvalidAddress = function(name, index, max) return { 'fcpu-errors.invalid-address', name, index, max } end,

  DivisionByZero = function() return { 'fcpu-errors.division-by-zero' } end,
  RegisterExpected = function() return { 'fcpu-errors.register-expected' } end,
  OutOfRange_Output = function() return { 'fcpu-errors.out-of-range-output' } end,
  InputChannelUnavailable = function() return { 'fcpu-errors.input-channel-unavailable' } end,

  StringNotTerminated = function() return { 'fcpu-errors.string-not-terminated' } end,
  TypeShouldBeSpecified = function() return { 'fcpu-errors.type-should-be-specified' } end,
  MinLtMax = function() return { 'fcpu-errors.min-lt-max' } end,
  UnknownItemName = function() return { 'fcpu-errors.unknown-item-name' } end,
  NilChannel = function() return { 'fcpu-errors.nil-channel' } end,
  NeedSignalid = function() return { 'fcpu-errors.need-signalid' } end,
  InvalidNilAddress = function() return { 'fcpu-errors.invalid-nil-address' } end,

  StackUnderflow = function() return { 'fcpu-errors.stack-underflow' } end,
  StackOverflow = function() return { 'fcpu-errors.stack-overflow' } end,
  StackOOB = function() return { 'fcpu-errors.stack-out-of-bounds' } end,
}

return Errors
